
DROP TABLE IF EXISTS pharmacy;
 
CREATE TABLE pharmacy (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  cash_balance DECIMAL(15,4) NOT NULL,
);

DROP TABLE IF EXISTS opentime;

CREATE TABLE opentime (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  pharmacy_id INT NOT NULL,
  opentime TIME NOT NULL,
  closetime TIME NOT NULL,
  openweek VARCHAR(250) NOT NULL,
);

DROP TABLE IF EXISTS mask;

CREATE TABLE mask (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  pharmacy_id INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  price DECIMAL(15,4) NOT NULL,
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  cash_balance DECIMAL(15,4) NOT NULL,
);

DROP TABLE IF EXISTS PURCHASE_HISTORIES;

CREATE TABLE PURCHASE_HISTORIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id INT NOT NULL,
  pharmacy_id INT NOT NULL,
  mask_id INT NOT NULL,
  TRANSACTION_AMOUNT DECIMAL(15,4) NOT NULL,
  transaction_Date TIMESTAMP NOT NULL,
);



